# Generated by Django 3.1.6 on 2021-02-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('image_seo', models.CharField(max_length=200)),
                ('review_title', models.CharField(max_length=200)),
                ('review_description', models.TextField()),
                ('bonus_link', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
