# Generated by Django 3.1.6 on 2021-02-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('affiliate_link', models.URLField(blank=True)),
                ('side_banner', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('main_banner', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('image_seo', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
