# Generated by Django 3.1.6 on 2021-02-10 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('competition_name', models.CharField(max_length=200)),
                ('home_team', models.CharField(max_length=200)),
                ('away_team', models.CharField(max_length=200)),
                ('kick_off_time', models.TimeField(default=datetime.datetime.now)),
                ('date_of_match', models.DateField(default=datetime.datetime.now)),
                ('prediction', models.CharField(max_length=200)),
                ('match_odds', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('betslip_link', models.URLField(blank=True)),
                ('bookmaker', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('image_seo', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
