# Generated by Django 3.1.6 on 2021-02-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Tip',
        ),
    ]
